### ISSUE TITLE
Not appearing in plugins list

### ISSUE THREAD

**Issue by simenbrekken** [airtype/restfulapi#1]
Tried installing this plugin after trying https://github.com/pixelandtonic/ElementAPI (which works) but after cloning the repo into `craft/plugins` it doesn't appear in the admin plugins list.

**Comment by wesrice** [comment]
@simenbrekken Just letting you know that I'm looking into it.

**Comment by simenbrekken** [comment]
@wesrice Great, let me know if you need anything from me, like configs etc.

**Comment by wesrice** [comment]
@simenbrekken Just checking, is the Restful Api plugin directory named `restfulapi` in your `craft/plugins` directory?
