### ISSUE TITLE
Simple endpoint

### ISSUE THREAD

**Issue by 1stevengrant** [airtype/restfulapi#4]
Wes,
Please excuse my ignorance. If I wanted to query the entries in a section where the post day was

`craft.entries.section('jobs').postDate('>= ' ~ now|date_modify('-90 days')`

how would I access that as an API call?

**Comment by wesrice** [comment]
Give this a try:

`/api/Entry?section=jobs&postDate=>=YYYY-MM-DD HH:MM:SS`

You'll need to do the calculation of the timestamp of now minus 90 days, and add it to your query string.

**Comment by 1stevengrant** [comment]
Perfect
