### ISSUE TITLE
Example of creating a new entry using POST

### ISSUE THREAD

**Issue by timbolimboslice** [airtype/restfulapi#9]
Hi there,

I've been struggling to save new entries using the POST method. Either I get a 422 error saying I'm missing a title, or I get a 500 error saying:

"array_key_exists() expects parameter 2 to be array, null given (/Users/MacbookPro/GitHub/flatfile/app/craft/app/models/BaseModel.php:418)"

I'm able to do a GET just fine. Could you show an extremely simple example of a POST creating a new entry with a title and a section id?

Many thanks!

**Comment by green-plastic** [comment]
I know this is deprecated but did you happen to figure this out?

**Comment by timbolimboslice** [comment]
I actually ended up figuring it out shortly after posting that message.

I ended up using this plugin here (not related to the original issue):
http://www.lookthinkco.de/oneprop/rentals. Hasn't launched yet, but should
in a week or so. 
Tim

On Thu, Jun 2, 2016 at 11:51 AM, Erik Wiedeman notifications@github.com
wrote:

> I know this is deprecated but did you happen to figure this out?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/airtype/restfulapi/issues/9#issuecomment-223352463,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALHf8WJCfsKGenHidEk9eD0Y_PONNrxaks5qHwoRgaJpZM4HC3cV
> .

## 

---

www.timbiery.com

**Comment by green-plastic** [comment]
What was the plugin? That link looks like a property website. Thanks.

**Comment by timbolimboslice** [comment]
My apologies, that link only shows how to do a GET on a list of entries. For creating new entries, I ended up just submitting a form to the action "entries/saveEntry". The user would have to be logged in for the entry to save. Try taking a look at this plugin too for guest entries: https://github.com/pixelandtonic/GuestEntries

Here is what mine looked like: 

```
<form method="post" accept-charset="UTF-8" class="entity-entry">
        {{ getCsrfInput() }}
        <input type="hidden" name="action" value="entries/saveEntry">
        <input type="hidden" name="sectionId" value="7">
        <input type="hidden" name="enabled" value="1">

        <label for="title">Title</label>
        <input id="title" type="text" name="title">

        <label>ext url</label>
        <input type="text" id="fields-externalUrl" name="fields[externalUrl]" value="" autocomplete="off" placeholder="">

        <input type="hidden" id="fields-dateAdded-date" name="fields[dateAdded][date]" value="{{ "now"|date("m/d/Y") }}" autocomplete="off">

        <input type="submit" value="add band">
    </form>
```

And the js.

```
$(".entity-entry").submit(function(e) {
        e.preventDefault();
        var data = $(this).serialize();
        $.post("entries/saveEntry", data, function(response) {
            if (response.success) {
                console.log("yay " + response.title);
            }
        });
    });
```

Hope that helps.

**Comment by jlevinsohn31** [comment]
@airtype - i want to use this plugin even tho it is deprecated and like the user above I am unable to use POST to create a new entry. When I run the POST in postman I get `Trying to get property of non-object`. Is there something I'm doing wrong here?

Any help greatly appreciated.
